name: MapperCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - uses: actions-rs/cargo@v1
      name: Build
      with:
        command: build 
        args: --verbose
    - uses: actions-rs/cargo@v1
      name: Test
      with:
        command: test 
        args: --verbose